name: Run Cypress and Deploy Report

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --force --legacy-peer-deps

      - name: Verify Cypress binary
        run: npx cypress install

      - name: Run Cypress tests
        run: npx cypress run --reporter mochawesome --reporter-options overwrite=false,html=true,json=true,reportDir=cypress/reports/html

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-report
          path: cypress/reports/html

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cypress/reports/html
          publish_branch: gh-pages
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
         SLACK_CHANNEL: "#cypress-reporting"
         SLACK_WEBHOOK: ${{ secrets.SECRET_WEBHOOK }}
         SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
         SLACK_ICON: https://github.com/rtCamp.png?size=48
         SLACK_MESSAGE: 'Bug Report https://github.com/navneetqa26/startnimbleproject/actions/runs/${{github.run_id}}'
         SLACK_TITLE: Post Title