name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
         SLACK_CHANNEL: "#cypress-reporting"
         SLACK_WEBHOOK: ${{ secrets.SECRET_WEBHOOK }}
         SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
         SLACK_ICON: https://github.com/rtCamp.png?size=48
         SLACK_MESSAGE: 'Bug Report https://github.com/navneetqa26/startnimbleproject/actions/runs/${{github.run_id}}'
         SLACK_TITLE: Post Title